api_platform:
    title: Bibliothèque API
    description: API REST d'emprunt de livres pour une bibliothèque municipale.
    version: 1.0.0
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
